spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3302/backend
    username: root
    password: 1234
#    docker run -it --rm --name spring-database -e MYSQL_USERNAME=springboot -e MYSQL_PASSWORD=syspass -e MYSQL_DATABASE=backend -e MYSQL_ROOT_PASSWORD=1234 -p 3302:3306 -d mysql
